services:
  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./product-only-prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - product-prom-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=6h
      - --web.enable-remote-write-receiver

  mysqld-exporter-product:
    image: prom/mysqld-exporter:v0.14.0
    container_name: mysqld-exporter-product
    restart: unless-stopped
    environment:
      DATA_SOURCE_NAME: "root:root@(10.0.1.33:3306)/"

volumes:
  product-prom-data:
