global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: product
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["10.0.1.23:8084"]
        labels: { host: product }
      - targets: ["10.0.1.24:8084"]
        labels: { host: product-a }
      - targets: ["10.0.1.25:8084"]
        labels: { host: product-b }
      - targets: ["10.0.1.26:8084"]
        labels: { host: product-c }
      - targets: ["10.0.1.27:8084"]
        labels: { host: product-d }

  - job_name: node
    static_configs:
      - targets: ["10.0.1.10:9100"]
        labels: { host: k6 }
      - targets: ["10.0.1.23:9100"]
        labels: { host: product }
      - targets: ["10.0.1.24:9100"]
        labels: { host: product-a }
      - targets: ["10.0.1.25:9100"]
        labels: { host: product-b }
      - targets: ["10.0.1.26:9100"]
        labels: { host: product-c }
      - targets: ["10.0.1.27:9100"]
        labels: { host: product-d }
      - targets: ["10.0.1.33:9100"]
        labels: { host: mysql-product }
      - targets: ["10.0.1.41:9100"]
        labels: { host: redis-product }

  - job_name: mysql
    static_configs:
      - targets: ["mysqld-exporter-product:9104"]
